### ISSUE TITLE
CORS verhindert data-include bei Browser-Ansicht auf lokaler Maschine

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/stoeberspecs#1]
Ich arbeite lokal an dem aktuellen Entwurf von hs-oer-lom und möchte mir meine Änderungen im Browser anschauen. Aufgrund von CORS können momentan keine mit `data-include` referenzierten Dateien eingebettet werden. Beispielhafte Fehlermeldung aus der Konsole: 

> Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf file:///home/acka47/git/hs-oer-lom-profil/draft/examples/general-example.xml. (Grund: CORS-Anfrage war nicht http).

Kann man da was machen, @sebastian-meyer ?

**Comment by sebastian-meyer** [comment]
Cross Origin Resource Sharing (CORS) ist ein Sicherheitsfeature moderner Browser, das verhindert, dass Daten über Domänengrenzen hinweg verarbeitet werden, sofern der Remote Host das nicht explizit erlaubt. Dazu muss der Remote Host einen entsprechenden Header setzen (`Access-Control-Allow-Origin: *`).

Bei lokal per file-Protokoll inkludierten Dateien funktioniert das leider nicht. Ich kenne da auch keinen Workaround außer sich lokal einen Webserver zu installieren und den oben beschriebenen Header zu konfigurieren. Dann kann das `data-include` über http erfolgen.

**Comment by acka47** [comment]
Ok, danke für die Klärung. Dann können wir da also nichts fixen und ich schließe das Ticket.
