### ISSUE TITLE
Verlinken des Dokuments in Spec Repos

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/stoeberspecs#3]
Das [Prozessdokument](https://dini-ag-kim.github.io/oer-stoeberspecs/) sollte in den READMEs folgender Repos verlinkt sein:

- [x] https://github.com/dini-ag-kim/hs-oer-lom-profil
- [x] https://github.com/dini-ag-kim/schulfaecher
- [x] https://github.com/dini-ag-kim/hcrt
- [x] https://github.com/dini-ag-kim/hochschulfaechersystematik

**Comment by acka47** [comment]
Wir sollten hier eine Formulierung für kontrollierte Vokabulare und eine für Metadatenprofile erarbeiten und dann die READMEs aktualisieren.

**Comment by acka47** [comment]
> Wir sollten hier eine Formulierung für kontrollierte Vokabulare und eine für Metadatenprofile erarbeiten und dann die READMEs aktualisieren.

Hier ein Entwurf für kontrollierte Vokabulare am Beispiel von HCRT:

> # HCRT – Hochschulcampus Ressourcentypen
>
> Die Hochschulcampus Ressourcentypen (HCRT) sind ein kontrolliertes Vokabular für Typen von Lernressourcen, gepflegt von der [OER-Metadatengruppe der DINI-AG KIM](https://wiki.dnb.de/display/DINIAGKIM/OER-Metadatengruppe). Das Vokabular wird referenziert in den Spezifikationen [LOM for Higher Education OER Repositories](https://w3id.org/kim/hs-oer-lom-profil/latest/) und dem in der Entwicklung befindlichen [LRMI-Profil](https://github.com/dini-ag-kim/lrmi-profile).
>
> ## Maintainer\*innen
>
> [Michael Menzel](https://github.com/mic-men) und [Adrian Pohl](https://github.com/acka47) 
>
> ## Status
>
> Veröffentlicht
>
> ## Entwicklung und Publikation
>
> In der Entwicklung des Vokabulars nutzen wir die [StöberSpecs](https://dini-ag-kim.github.io/stoeberspecs/)-Wekzeuge und -Prozesse. Das Vokabular wird in diesem [GitHub Repo](https://github.com/dini-ag-kim/hcrt) in der Datei [hcrt.ttl](https://github.com/dini-ag-kim/hcrt/blob/master/hcrt.ttl) versioniert und gepflegt. Als Beschreibungssprache wird das [Simple Knowledge Organization System (SKOS)](https://www.w3.org/2004/02/skos/) in [Turtle](https://www.w3.org/TR/turtle/)-Syntax verwendet. Die offizielle Publkikation erfolgt unter der URI [https://w3id.org/kim/hcrt/scheme](https://w3id.org/kim/hcrt/scheme) mit [SkoHub-Vocabs](https://github.com/hbz/skohub-vocabs), einer grafischen Präsentation des Vokabulars mit weitergehenden Möglichkeiten wie einer Suchfunktion. 
>
> ## Mitarbeit und Kontakt
>
> Mitarbeit und Kontakt findet am besten statt über [Issues](https://github.com/dini-ag-kim/hcrt/issues) oder die [Mailingliste der OER-Metadatengruppe](http://lists.dnb.de/mailman/listinfo/dini-ag-kim-oer).

**Comment by sroertgen** [comment]
https://github.com/dini-ag-kim/schulfaecher wurde gemerged ✅

**Comment by acka47** [comment]
Erledigt
